README.md
license.md

Modify the README file and add a license

Modify the README file and add a license

---

app/controllers/positions_controller.rb
app/helpers/positions_helper.rb
app/models/portfolio.rb
app/models/position.rb
app/views/positions/_form.html.erb
app/views/positions/_position.html.erb
app/views/positions/_position.json.jbuilder
app/views/positions/edit.html.erb
app/views/positions/index.html.erb
app/views/positions/index.json.jbuilder
app/views/positions/new.html.erb
app/views/positions/show.html.erb
app/views/positions/show.json.jbuilder
config/routes.rb
db/migrate/20220704184355_create_positions.rb
db/schema.rb

Generated the Position scaffold, change the routes, and update the models.

Generate Position scafold

---

app/controllers/application_controller.rb
app/controllers/portfolios_controller.rb
app/controllers/positions_controller.rb
app/controllers/users_controller.rb
app/models/portfolio.rb
app/models/user.rb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/layouts/application.html.erb
app/views/portfolios/_portfolio.html.erb
app/views/portfolios/index.html.erb
config/initializers/devise.rb

User model

---

app/controllers/positions_controller.rb
app/controllers/transactions_controller.rb
app/helpers/transactions_helper.rb
app/models/portfolio.rb
app/models/transaction.rb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_links.html.erb
app/views/layouts/application.html.erb
app/views/transactions/_form.html.erb
app/views/transactions/_transaction.html.erb
app/views/transactions/_transaction.json.jbuilder
app/views/transactions/_update.html.erb
app/views/transactions/edit.html.erb
app/views/transactions/index.html.erb
app/views/transactions/index.json.jbuilder
app/views/transactions/new.html.erb
app/views/transactions/show.html.erb
app/views/transactions/show.json.jbuilder
config/routes.rb
db/migrate/20220712161651_create_transactions.rb
db/migrate/20220712162130_add_portfolio_ref_to_transaction.rb
db/schema.rb

In this PR the transactions controller and model have been created. Add transactions model into the portfolio and made the necessary changes in routing and views. Styled the login screen.

Transaction

---

Gemfile
Gemfile.lock
app/controllers/portfolios_controller.rb
app/helpers/portfolios_helper.rb
app/views/portfolios/_portfolio.html.erb

Add finnhub-ruby gem and get the stock price from their API.

Add Price from Finnhub API

---

.gitignore
Gemfile
Gemfile.lock
app/helpers/portfolios_helper.rb
config/environment.rb

Add application environment variables in a separate file and made the appropriate changes in the ApiCall.

Add env_car file for API credentials

---

app/helpers/portfolios_helper.rb
app/views/portfolios/_portfolio.html.erb
app/views/portfolios/index.html.erb

Fix the problem with total Gain and Gain % when there are no stock positions. It includes the current P/L and Realized P/l and shows the total Gain or Loss and % of that.

Finaly the P/L and Gain, Gain% is fixed and working as expected

---

app/controllers/stocks_controller.rb
app/helpers/stocks_helper.rb
app/models/stock.rb
app/views/stocks/_form.html.erb
app/views/stocks/_stock.html.erb
app/views/stocks/_stock.json.jbuilder
app/views/stocks/edit.html.erb
app/views/stocks/index.html.erb
app/views/stocks/index.json.jbuilder
app/views/stocks/new.html.erb
app/views/stocks/show.html.erb
app/views/stocks/show.json.jbuilder
config/routes.rb
db/migrate/20220803210354_create_stocks.rb

Add a new Stock Controller, model, and views.

Add a Stock model

---

app/controllers/portfolios_controller.rb
app/helpers/transactions_helper.rb
app/views/portfolios/_portfolio.html.erb

Add realized_profit_loss field and value in the portfolio. Coloring accordingly.

Add realized profit loss per stock position.

---

app/controllers/positions_controller.rb
app/controllers/stocks_controller.rb
app/controllers/transactions_controller.rb
app/helpers/transactions_helper.rb
app/views/portfolios/_portfolio.html.erb
app/views/positions/_new.html.erb
app/views/stocks/_form.html.erb
db/migrate/20220704184355_create_positions.rb
db/migrate/20220803210354_create_stocks.rb
db/schema.rb

The problem with the total portfolio realized profit loss is not fixed for a partial position. Check it out next.

Fixing the Realized profit loss for stock and portfolio.

---

app/controllers/portfolios_controller.rb
app/helpers/portfolios_helper.rb
app/helpers/transactions_helper.rb
app/views/portfolios/_portfolio.html.erb

The realized profit loss is incorrectly calculated for multiple portfolios cases. Check it out.

Still a problem with multiple portfolios for RPL

---

app/controllers/portfolios_controller.rb
app/controllers/stocks_controller.rb
app/controllers/transactions_controller.rb
app/helpers/transactions_helper.rb
app/models/portfolio.rb
app/models/stock.rb
app/views/portfolios/_form.html.erb
app/views/portfolios/_portfolio.html.erb
app/views/stocks/_form.html.erb
db/migrate/20220704155359_create_portfolios.rb
db/migrate/20220803210354_create_stocks.rb
db/schema.rb

Adding a new field to the stock model - portfolio_id. Fixing bug with incorrect profit loss in multiple portfolios view.

Stocks refact

---

app/controllers/portfolios_controller.rb
app/helpers/portfolios_helper.rb
app/helpers/transactions_helper.rb
app/models/portfolio.rb
app/views/portfolios/_form.html.erb
app/views/portfolios/_portfolio.html.erb
db/migrate/20220704155359_create_portfolios.rb
db/schema.rb
db/seeds.rb

Introduced a new field in the Portfolios table - transactions_cost. Fix the bug of incorrect Realized C/F in multiple portfolios scenario.

Fix the bug in realized C/F between portfolios!

---

app/views/stocks/_stock.html.erb

Add rel = noopener for external links.

Add rel to external links and some styling

---

app/controllers/positions_controller.rb
app/controllers/stocks_controller.rb
app/controllers/transactions_controller.rb
app/helpers/portfolios_helper.rb
app/helpers/positions_helper.rb
app/helpers/transactions_helper.rb
app/views/portfolios/_portfolio.html.erb
db/migrate/20220704184355_create_positions.rb

Add the Buy to Cover transaction. Fix the bug by not updating the realized Profit Loss. It was a simple speel error - instead of 'Sell short' I had 'Sell Short' in the helper. It took me several hours to find it!!!

Transactions

---

config/environments/production.rb

Change the production file to use the master key

Change the production file to use the master key

---

Gemfile
Gemfile.lock
app/views/portfolios/_portfolio.html.erb
config/environments/development.rb

Fix the bug where the stock was only tight to a ticker, but not the portfolio_id.

Errors fix

---

app/assets/stylesheets/application.css
app/helpers/users_helper.rb
app/models/user.rb
app/views/devise/shared/_links.html.erb

Added helper method ofr user's gravatar_for(user) and change the path for Gmail logo by removing the /assets/

Validation

---

app/controllers/portfolios_controller.rb
app/controllers/positions_controller.rb
app/controllers/stocks_controller.rb
app/controllers/transactions_controller.rb
app/helpers/portfolios_helper.rb
app/helpers/positions_helper.rb
app/helpers/transactions_helper.rb

Refactoring the portfolios, transactions, stocks and positions controllers.

Refactoring

---

app/controllers/positions_controller.rb
app/controllers/stocks_controller.rb
app/models/user.rb

Remove unused codes

---

.vscode/settings.json
Gemfile.lock
app/controllers/transactions_controller.rb
app/helpers/transactions_helper.rb
app/javascript/controllers/forms_controller.js
app/javascript/controllers/hello_controller.js
app/models/portfolio.rb
app/views/layouts/application.html.erb
app/views/portfolios/_form.html.erb
app/views/transactions/_form.html.erb
app/views/transactions/_transaction.html.erb
app/views/transactions/new.html.erb
config/routes.rb
db/migrate/20220712161651_create_transactions.rb
db/schema.rb
package-lock.json

Now you can add Cash In and Cash Out transactions to your portfolio. They allow you to add or remove cash (which should be available in your portfolio).

Two new transactions added

---

app/views/transactions/_form.html.erb

Add Dividend type transaction in the transaction form.

Add Dividend type transaction

---

app/helpers/portfolios_helper.rb
app/helpers/transactions_helper.rb
app/views/portfolios/_portfolio.html.erb
app/views/portfolios/index.html.erb

Implemented a new row in the portfolios table showing the Realized P/L, Income and Realized C/F figures for closed positions.

Closed positions

---

Gemfile
Gemfile.lock
app/controllers/transactions_controller.rb
app/helpers/transactions_helper.rb
app/javascript/controllers/forms_controller.js
app/views/portfolios/_portfolio.html.erb
app/views/stocks/_stock.html.erb
app/views/stocks/_stock_news.erb
app/views/transactions/_form.html.erb
app/views/transactions/_transaction.html.erb
app/views/transactions/index.html.erb
config/environments/development.rb

Implemented 'Stock Split' transaction. The forms_controller.js have been re-written to reflect the changes and to optimized a common code.
There was a problem with the gem bullet giving me an error: "`Problem uninitialized constant #<Class:UniformNotifier::SentryNotifier>::Sentry`"
So, I disabled the gem until the problem is solved.

Stock split

---

app/controllers/transactions_controller.rb
app/javascript/controllers/forms_controller.js
app/views/transactions/_form.html.erb

Implemented a field in the transaction form for 'Symbol Change' type.
Implemented the hide/show fields in the forms_controller.
Add the case for "Symbol Change" in transaction controller.

Ticker change

---

app/controllers/transactions_controller.rb
app/helpers/transactions_helper.rb
app/javascript/controllers/forms_controller.js
app/views/portfolios/_form.html.erb
app/views/portfolios/_portfolio.html.erb
app/views/stocks/_stock.html.erb
app/views/transactions/_form.html.erb
app/views/transactions/_transaction.html.erb
app/views/transactions/index.html.erb
app/views/transactions/show.html.erb

Implemented Symbol Change transaction.
Clean up code.
Refactoring style classes and forms_controller.js

Symbol change

---

config/environments/production.rb

Add the changes for the confirmable email to the production environment.

Made confirmable email in production

---

.github/workflows/linters.yml
README.md

Change the linters.yml file to the latest one.

Production

---

app/views/devise/mailer/email_changed.html.erb
app/views/devise/mailer/password_change.html.erb
app/views/devise/mailer/reset_password_instructions.html.erb
app/views/devise/mailer/unlock_instructions.html.erb
app/views/devise/passwords/new.html.erb

The rest of the email templates like: reset password, password changed, email changed, and unlock account have been styled.

Emails styles

---

app/helpers/users_helper.rb
app/views/devise/registrations/edit.html.erb
app/views/transactions/new.html.erb

Styling the edit credentials form and minor changes.

Styling the edit credentials form

---

app/assets/stylesheets/application.css
app/controllers/users_controller.rb
app/helpers/users_helper.rb
app/views/devise/registrations/edit.html.erb
app/views/layouts/application.html.erb
app/views/transactions/_form.html.erb
app/views/users/show.html.erb

Implemented an edit profile page, where users can change the email and the password for their account.

Edit profile implemented

---

app/helpers/users_helper.rb
app/views/users/show.html.erb

For now, the User show page is completed with statistics, including:
Best and Worst open dividend income/losses
Best and Worst closed dividend income/losses

Refactoring show page, by adding positions_stats method in user_helper

---

app/controllers/transactions_controller.rb
app/helpers/transactions_helper.rb
app/javascript/controllers/forms_controller.js
app/views/transactions/_form.html.erb
app/views/transactions/_transaction.html.erb

The last two transactions added to the application - "Shares in" and "Shares out". For the "Shares in" transaction a 0 price per share is allowed, so users can record gift shares or matching shares for the company's matching plan.

Shares in and Shares out transactions implemented.

---

app/views/transactions/_form.html.erb

Change the remarks text on the form page

---

app/views/transactions/_form.html.erb

Modify styling on the remarks on the New Transaction form.

Form styling

---

Gemfile
Gemfile.lock
app/controllers/transactions_controller.rb
app/models/transaction.rb
app/views/transactions/index.html.erb

Adding sort for the transactions table.

Pagination
